version: '3'

services: 
  app: 
    build: .
    command: yarn start
    ports: 
      - '9100:9100'

    volumes: 
      - .:/usr/app

  db:
    container_name: 'database-softbarber'
    image: mariadb
    restart: always
    ports: 
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root

